name: Automated Release

on:
  push:
    tags:
      - "v*.*.*"
      - "!v*.*.*-dev"
      - "!v*.*.*-beta"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Download and install install4j
        run: wget https://download-gcdn.ej-technologies.com/install4j/install4j_linux_8_0_11.deb && sudo dpkg -i install4j_linux_8_0_11.deb
      - name: Build with Gradle
        run: ./gradlew build media -x test
        env:
          INSTALL4J_HOME: /opt/install4j8
          INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}
          DEV_STAGE: 2
      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(./gradlew printVersion | grep 'version=' | sed 's/version=//')"
        env:
          INSTALL4J_HOME: /opt/install4j8
          INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            build/artefacts/**
          name: tag_stable
          body: ${{ steps.get_version.outputs.version }}
          body_path: src/main/resources/release_notes.md
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: |
            build/artefacts/**
          name: ${{ steps.get_version.outputs.version }}
          body_path: src/main/resources/release_notes.md
